### ISSUE TITLE
Missing VPN Connect Event 

### ISSUE THREAD

**Issue by chizou** [deanmcniven/wsl2-vpn-support#2]
I get this is more of a GlobalProtect/Windows issue, but I figured it'd be good to at least post for awareness:

I'm having an issue getting the Task Scheduler to detect the VPN connection event and consequently, execution of the script. Looking in Windows Event Viewer, I don't an 10000/10001 event being generated on VPN connect/disconnect. You can see for yourself in Event Viewer under Applications and Services Logs -> Microsoft -> Windows -> NetworkProfile -> Operational.

I ended up doing the following to get it to work: https://docs.paloaltonetworks.com/globalprotect/8-0/globalprotect-admin/globalprotect-clients/deploy-agent-settings-transparently/deploy-agent-settings-to-windows-clients/deploy-scripts-using-the-windows-registry

**Comment by MonicaTiyyagura** [comment]
Hi @chizou 
Should we give the path of the same script when giving the value data for command. What is %userprofile%\pre_vpn_connect.bat c: test_user, I do not understand this
